version: '3.8'

services:
  springboot-app:
    image: ms-stats:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - SPRING_RABBITMQ_HOST=rabbitmq

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  aws-cli:
    image: amazon/aws-cli
    container_name: aws-cli
    depends_on:
      - dynamodb-local
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
    # Conectamos a la misma red interna de docker-compose
    networks:
      - default
