aws:
  dynamodb:
    accessKey: EMPTY
    secretKey: EMPTY
    endpoint: http://localhost:8000
    region: us-west-2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest